### ISSUE TITLE
CORS preflight issue

### ISSUE THREAD

**Issue by iranicus** [ralscha/blog#10]
Heys, thanks for taking the time to make the tutorial it is exactly something which I hope to implement in my ionic 3 project, I seem to have ran into a CORS issue however when I try to make any request from the app when testing it in the chrome browser with "ionic serve --lab", in the console I get the following:

OPTIONS http://localhost:8080/login 401 ()
Failed to load http://localhost:8080/login: Response for preflight has invalid HTTP status code 401.

Having had a read around it seems like a CORS issue with the configuration in Spring Boot, I have tried various ways with adding a CORS filter to the backend server but haven't had any success with this. Any thoughts?

**Comment by ralscha** [comment]
Hi
I think I had a similar issue with an older spring-security version. What version of spring and spring-security do you use?

**Comment by iranicus** [comment]
Thanks for the quick response, so taking a look the versions are:
Spring: 5.0.5.RELEASE
Spring Boot: 2.0.1.RELEASE
Spring Security Core: 5.0.4.RELEASE

**Comment by ralscha** [comment]
Same I use for my demo.

Have you added the `cors()` configuration in the security config
```
		http
		  .cors()    // <---------
		    .and()

```
https://github.com/ralscha/blog/blob/master/jwt/server/src/main/java/ch/rasc/jwt/security/SecurityConfig.java

**Comment by iranicus** [comment]
I have indeed I have the same setup for the server you have in the repo, in the security config:
```
    protected void configure(HttpSecurity http) throws Exception {
        http
                .csrf().disable()
                .cors().and()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
                // .httpBasic().and() //optional, if the service wants to be accessed via the browser
                .authorizeRequests()
                    // endPoint configuration requiring authorization
                    .antMatchers("/signup").permitAll()
                    .antMatchers("/login").permitAll()
                    .antMatchers("/public").permitAll()
                    .anyRequest().authenticated().and()
                .apply(new JWTConfigurer(this.tokenProvider));
    }
```

**Comment by ralscha** [comment]
Is there also a `@CrossOrigin` annotation on the Controller class where the /login mapping is located?

```
@RestController
@CrossOrigin
public class AuthController {

 @PostMapping("/login")
  public String authorize(@Valid @RequestBody User loginUser,
      HttpServletResponse response) {
      .....
  }
}
```

**Comment by iranicus** [comment]
Indeed I have, I have uploaded my current server code in a repo on (https://github.com/iranicus/JWT_attempt) if you could take a ganders pls :>

**Comment by ralscha** [comment]
I will look tomorrow. 

One quick thing you could try is to remove 
```
spring.mvc.dispatch-options-request=true
```
in your application.properties file.

**Comment by iranicus** [comment]
Will do that was just added as part of a potential CORS fix, just removed it now but unfortunately no change.

**Comment by ralscha** [comment]
I have just tested my application and it works. I will try your project tomorrow. 

![2018-05-06 22_20_36-developer tools - http___localhost_8100_](https://user-images.githubusercontent.com/372512/39677618-96fd37c0-517e-11e8-8480-39a0e40b56ae.png)

![2018-05-06 22_20_55-developer tools - http___localhost_8100_](https://user-images.githubusercontent.com/372512/39677619-98c0ce96-517e-11e8-90a3-8e0d007b5475.png)

**Comment by ralscha** [comment]
It works when you remove
``` 
//@ComponentScan({ "com.rdanby.jwt.security.jwt" })
```
on the JwtApplication class. This annotation only configures beans in the com.rdanby.jwt.security.jwt package and skips everything else

and add @Component on the TokenProvider, because the application needs to inject this bean into other beans.
```
@Component
public class TokenProvider {
```

**Comment by iranicus** [comment]
Just added this now and it has fixed the issue, thanks loads. There is another issue I have ran into however with the /secret and /authenticate api calls which I'll bring up as a different issue.
