### ISSUE TITLE
[ionic] ts error: FileEntry not found

### ISSUE THREAD

**Issue by hnguyen48206** [ralscha/blog#16]
Hi, 
I'm trying to apply your example to my ionic project which I need to send a video file to a server by using a REST api accepting form-data. After following steps from this article: https://golb.hplar.ch/2017/02/Uploading-pictures-from-Ionic-2-to-Spring-Boot.html
Now I'm facing a problem with the ts error that couldn't understand <FileEntry>

```
 this.file.resolveLocalFilesystemUrl(imageFileUri)
      .then(entry => (<FileEntry>entry).file(file => this.readFile(file)))
      .catch(err => console.log(err));
```
Do you have any suggestion on how to resolve this? Thanks a lot.

**Comment by ralscha** [comment]
Hi
What TypeScript version do you use?

**Comment by ralscha** [comment]
One thing you can try is using async/await

```
  private async uploadPhoto(imageFileUri: any): Promise<void> {
    this.error = null;
    this.loading = this.loadingCtrl.create({
      content: 'Uploading...'
    });

    this.loading.present();

    try {
      const entry = <FileEntry> await this.file.resolveLocalFilesystemUrl(imageFileUri);
      entry.file(file => this.readFile(file));
    } catch(e) {
      console.log(e);
    }
  }
```

**Comment by hnguyen48206** [comment]
Thank you sir for your kind response :D, I've found out the problem lying in the way of type casting. Instead of the old way, I changed it to **_entry as FileEntry_** and it worked just fine.

However, now another problem has risen which I have no clue of how. On emulator, my ionic app has successfully uploaded video file to a server but when running on real device, I always encounter the 404 error that the endpoint could not be found. Really appreciate if you can help me with any suggestion

Below is my code, start with **videosSender()** and the file path has been saved in **rawVideoPath** varaiable (has the form: **file:///storage/emulated/0/DCIM/Camera/VID_20180709_223200.mp4**)
```
videosSender() {    
    if (this.rawVideoPath.startsWith("file")) {
      this.file.resolveLocalFilesystemUrl(this.rawVideoPath)
        .then(entry => (entry as FileEntry).file(file => this.readFile(file)))
        .catch(err => console.log(err));
    }
    else {
      this.file.resolveLocalFilesystemUrl("file://" + this.rawVideoPath)
        .then(entry => (entry as FileEntry).file(file => this.readFile(file)))
        .catch(err => console.log(err));
    }
  }

  private readFile(file: any) {
    const reader = new FileReader();
    reader.onloadend = () => {
      const formData = new FormData();
      const imgBlob = new Blob([reader.result], { type: file.type });
      formData.append('uploadedFiles', imgBlob, file.name);
      formData.append('data', this.JWTEncode("videos"))
      this.postData(formData);
    };
    reader.readAsArrayBuffer(file);
  }
  private postData(formData: FormData) {  
    let url = "http://crm.eoc.vnptmedia.vn/api/app11x/upload-videos";
    let headers = new Headers({
     'enctype': 'multipart/form-data; boundary=----WebKitFormBoundaryuL67FWkv1CA'
     })
    let options = new RequestOptions({ headers: headers });
    this.http
      .post(url, formData)
      .map(res => res.json())
      .subscribe(
        data => {
          console.log(data);
          if (data.success == true) {
            this.loadingcounter -= 1
            if (this.loadingcounter == 0) {
              this.loading.dismiss();
              alert("Đã gửi thành công. Xin cảm ơn thông tin của bạn.")
              this.navCtrl.pop()
            }
          }
        },
        err => {
          this.loading.dismiss();
          alert(err);
        }
      );
  }
```

**Comment by ralscha** [comment]
Sorry. I have no idea. If it is working in an emulator it should work on a device too. 
Is the emulator and the device running with the same Android version?

**Comment by hnguyen48206** [comment]
It was due to the content security policy. Simply add this line to the index.html would fix it: 

meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com; style-src 'self' 'unsafe-inline'; media-src *"

Once again, thanks a lot for your support. 👍

**Comment by ralscha** [comment]
Thanks for the feedback. I will add it to my example

**Comment by hnguyen48206** [comment]
Sorry to bother you again :( , I'm currently working on a new Ionic project that also requires image uploading using form-data and http POST. I've encountered a really annoying matter that I could not figure out how to solve it and since I've followed the exact perfectly working code from the previous work that I opened this thread a few months ago for.

At the step that I need to use File Reader in order to convert the local file to st that can be sent to the API end-point, 60% of the times, the FileReader seems to take forever to run and it did not even fail (file size is really small, only around 200 KB), the process just kept running til I had to manually shut the app down. The part that I do not understand is that like I've mentioned, this only happened around 6/10 times of trying. Below is the related code piece, I appreciate any possible feedback. Thank you sir.

 ```
const reader = new FileReader();
    reader.onload = () => {
      console.log('ok to read file')
      console.log(reader.result)
      const formData = new FormData();
      const imgBlob = new Blob([reader.result], { type: file.type });
      formData.append('file', imgBlob, file.name);
      formData.append('body', data)
      this.postData(formData);
    };
    reader.onerror = () => {
      console.log('fail to read file')
      reader.abort()
      this.loading.dismiss()
    };
    reader.readAsArrayBuffer(file);
```

**Comment by ralscha** [comment]
One thing you can try is uploading the file without using the FileReader.
I think this should work because the second parameter of the `append()` method may be a File object     
https://developer.mozilla.org/en-US/docs/Web/API/FormData/append

```
     const formData = new FormData();
     formData.append('file', file, file.name);
     formData.append('body', data)
     this.postData(formData);
```

**Comment by hnguyen48206** [comment]
Thanks for your timely response. I've tried to upload the file without going through the FileReader, but it ended up to upload a null parameter "formData.append('file', file, file.name)" everytime. This is the exact process: passing a local file URL to the function avatarProcess() which would return a FileEntry, previously, this FileEntry will be passed to the FileReader before being appened to the form.

If I do it as the old way, like I said, I would get the success rate of 60% at FileReader, but without FileReader, it's just null.

```
 avatarProcess(path, data) {
    if (path.startsWith("http")) {
      const formData = new FormData();
      formData.append('file', null);
      formData.append('body', data)
      this.postData(formData);
    }
    else {
      if (path.startsWith("file")) {
        this.file.resolveLocalFilesystemUrl(path)
          .then(entry => {
            (entry as FileEntry).file(file => this.testUpload(file, data))
          })
          .catch(err => {
            console.log(err);
            this.loading.dismiss()
          }
          );
      }
      else {
        this.file.resolveLocalFilesystemUrl("file://" + path)
          .then(entry => {
            (entry as FileEntry).file(file => this.testUpload(file, data))
          })
          .catch(err => {
            console.log(err);
            this.loading.dismiss();
          }
          );
      }
    }
  }
testUpload(file, data) {
    console.log('testUpload')
    let formData = new FormData();
    formData.append('file', file, file.name) ;
    formData.append('body', data)
    this.postData(formData);
  }
```
