### ISSUE TITLE
console.log(reader.result )   is {}

### ISSUE THREAD

**Issue by yytian1017** [ralscha/blog#18]
Hello,  I'm trying to apply your example to my ionic project,
<img width="963" alt="2018-07-20 7 12 12" src="https://user-images.githubusercontent.com/20925213/42999571-dbaa1426-8c50-11e8-89af-4ea138479f88.png">

I console the reader.result, but it is {}.  I don't the reason.

**Comment by ralscha** [comment]
No clue. 
Something worth trying is adding 
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com; style-src 'self' 'unsafe-inline'; media-src *">
```
to the index.html

see #16

**Comment by yytian1017** [comment]
Thank you sir for your response.
On android, my ionic app has successfully uploaded img to a server but when running on ios,  the reader.result is {}. 

when I add <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com; style-src 'self' 'unsafe-inline'; media-src *">, ios buid failed

**Comment by ralscha** [comment]
Sorry. I have no idea what the problem is. 

Can you try to listen for the `load` instead of the `loadend` event

```
reader.onload = () => {
```

**Comment by ralscha** [comment]
Here a list of all supported events    
https://developer.mozilla.org/en-US/docs/Web/API/FileReader

**Comment by yytian1017** [comment]
I really appreciate for your kind response. hmm..., I do nothing, but today it's work.
