### ISSUE TITLE
[Ionic-4] - no longer working for me

### ISSUE THREAD

**Issue by loicsalou** [ralscha/blog#19]
Hi,
Rather than an issue, it's more some help I need... I applied all these great optimizations to my PWS, but now I'm trying to upgrade ionic the the v4-beta.0 but it seems that all the tooling changed, hence the scripts in the "config" section of the package.json seem to be no longer executed at build time.

I'm not really familiar with this, I hope you will find the way how to have this working with Ionic 4 !
Thanks in advance !

**Comment by ralscha** [comment]
Hi. What project are you referring to? The workbox example?

**Comment by loicsalou** [comment]
Yes. Workbox example.

Le dim. 29 juil. 2018 à 18:40, Ralph Schaer <notifications@github.com> a
écrit :

**Comment by ralscha** [comment]
When you only need support for caching and push notification I recommend to use the Angular Service Worker: https://angular.io/guide/service-worker-getting-started

You can add the Service Worker with this command
```
ng add  @angular/pwa --project *project-name*
```

And when you create a production build
```
ng build --prod
```
the Angular CLI takes care of everything.

The only downside of the Angular Service worker is that I haven't found a way to add custom code to the Service Worker. In this scenario you can write your own Service Worker.
See my blog post about this topic:
https://golb.hplar.ch/2018/06/workbox-serviceworker-in-angular-project.html

**Comment by loicsalou** [comment]
well, currently I implemented all of what you showed in your article https://golb.hplar.ch/2017/12/Workbox-in-Ionic-and-Lazy-Loading-Modules.html, which is more than simply the worker. This includes workbox, hash file names, server setup with compression (and bread-compressor in package-json). All of this relies on the fact that we add a "config" section to the package.json like
```
"config": {
...
 "ionic_webpack": "./webpack.config.js"
},
```
cache-busting.js is also complaining about not finding build-manifest.json, dunno why...
In the end all this does not seem to be still working with either ionic, or maybe @angular/cli@latest, I'm not sure. Maybe not everything is ready yet... or everything changed and I must learn this from scratch again.
So I wonder if I must restart all these optimisations from scratch or try to adapt what I have currently in ordre to make it work with ionic4 etc.

**Comment by ralscha** [comment]
I recommend using the [Angular Service Worker](https://angular.io/guide/service-worker-getting-started)
```
ng add @angular/pwa --project *project-name*
ng build --prod
```
This does everything you described (except compression). There is no need for a custom solution any more. 

If you need pre-compression you install the compressor
```
npm install bread-compressor-cli -D
```
and then add a task to the scripts section
```
"dist": "ng build --prod && bread-compressor www",
```

```
npm run dist
```

**Comment by loicsalou** [comment]
Ok, thank you, I tried but was unsuccessful so far. I will investigate
further then.

Le lun. 30 juil. 2018 à 12:53, Ralph Schaer <notifications@github.com> a
écrit :

**Comment by ralscha** [comment]
Josh Morony also wrote an article about this:      
https://www.joshmorony.com/create-a-pwa-with-angular-service-workers-in-ionic-4/

Make sure that you use the correct projectname when you run the command. `app` is the default. It has to match the project name in the file `angular.json`
```
ng add @angular/pwa --project app
```
