### ISSUE TITLE
Getting error in polyfills.js line 3 - calls to REST services are showing status as canceled

### ISSUE THREAD

**Issue by rsrinathr** [ralscha/blog#20]
I tries with both Ionic 4.1 and Cordova 8   as well as ionic 3.9.2 and Cordova 7.1.0
All the REST calls are showing status as cancelled in polyfills.js line 3. Please help

![image](https://user-images.githubusercontent.com/30648579/44954715-3c328180-ae5b-11e8-8fa4-76fc202bdc3d.png)

**Comment by ralscha** [comment]
Hi
Difficult to say. Do you see error messages on the server side?
Maybe a CORS issue?
