### ISSUE TITLE
Check if file is uploaded

### ISSUE THREAD

**Issue by PeterHdd** [ralscha/blog#22]
Hello,

Regarding this post:

https://golb.hplar.ch/2017/02/Uploading-pictures-from-Ionic-2-to-Spring-Boot.html

How do we check if the file is in the server?
In the end of the blog you said:
>When everything works, you should find the uploaded files in the root of the server application.

So we should find it if we do https://localhost:8080?

**Comment by ralscha** [comment]
Hi

You should find it in the root of your server project folder. 
Same directory where you find the files `pom.xml` and `mvnw`.

**Comment by PeterHdd** [comment]
Ohh okay, thank you. 

I'm getting “java.nio.file.AccessDeniedException” it is why I'm not seeing the file in that location.

**Comment by ralscha** [comment]
You can change the location. 

Change this line
https://github.com/ralscha/blog/blob/master/uploadsb/server/src/main/java/ch/rasc/upload/UploadController.java#L27

For example, on Windows, when you want to store the file into the directory `c:/upload`:
```
Path downloadedFile = Paths.get(file.getOriginalFilename()).resolve(Paths.get("c:/upload"));
```

**Comment by PeterHdd** [comment]
Happy new year and thank you so much, it worked!!
