### ISSUE TITLE
Crop image before upload it

### ISSUE THREAD

**Issue by atsoares** [ralscha/blog#23]
Hi, I'm using your tutorial to understand better how the camera component works, but I've stuck here and don't know how to implement crop component within your tutorial. Could you give me some example? I mess up when I need to convert the file, don't know how to call the crop method inside the "getPicture().then(..."

**Comment by ralscha** [comment]
I've never implemented a crop functionality, so I can't really help you there.

Here is an interesting crop component that I found with a search:     
https://github.com/Mawi137/ngx-image-cropper
