### ISSUE TITLE
POST http://localhost:8080/clienterror net::ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by aditbharadwaj** [ralscha/blog#24]
iam getting this error while running geotracker app ? what can be the issue ? why is it saying connection refused ?
HttpErrorResponse
error: ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: "error", …}
headers: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, headers: Map(0)}
message: "Http failure response for http://localhost:8080/clienterror: 0 Unknown Error"
name: "HttpErrorResponse"
ok: false
status: 0
statusText: "Unknown Error"
url: "http://localhost:8080/clienterror"

this error i received on both emulator and on a android device

**Comment by ralscha** [comment]
Hi
There is no server running on `localhost`. You have to specify the IP address of the server.

**Comment by ralscha** [comment]
If you want to test it on a real device I recommend [`ngrok`](https://ngrok.com/)
Start `ngrok` on your server: `ngrok http 8080`

Enter the https address in [environment.prod.ts](https://github.com/ralscha/blog/blob/master/geotracker/client/src/environments/environment.prod.ts). Build and install the app on the device

**Comment by aditbharadwaj** [comment]
i see, thank you so much for the quick reply , i will build with ngrok. 
i also have a query related to the uuid for the send the unique id , how do i install the uuid js library , if i follow the `npm install uuid` do i need to first navigate to the server folder in cmd to install it over their or will it be automatically installed in the server folder and which version should i choose?

**Comment by ralscha** [comment]
You have to run this command in the client folder. The folder where `package.json` resides. npm install automatically installs the latest version which should work with the code example.

**Comment by aditbharadwaj** [comment]
well i finally manage to build the app with all code properly build in but now after running the app on the device i get "Access to XMLHttpRequest at 'http://39678d08.ngrok.io/clienterror' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." while sending data to across server do i need to add some access or permissions ?

**Comment by ralscha** [comment]
Yes. You need to configure CORS. In Spring Boot you usually only need to add `@CrossOrigin` to the controller

**Comment by aditbharadwaj** [comment]
well at least the app is working with no error whatsoever in the console and data is transmitting accordingly.
thank you so much again 👍 will ask more if any help needed

**Comment by ralscha** [comment]
Great. You're welcome. Ask away if more questions arise
