### ISSUE TITLE
uploaded Image not rendered directly on screen

### ISSUE THREAD

**Issue by azzmiazzmi** [ralscha/blog#26]
Hello
thank for example, but there is strange issue:
the image uploaded successfully on server side, but not rendered directly on screen
unless i click one of tacking image buttons again.
thanks

**Comment by ralscha** [comment]
Looks like a refresh problem. What example are you referring to?

**Comment by azzmiazzmi** [comment]
Uploading pictures from Ionic 4 / Cordova to Spring Boot

في الأربعاء، ١٩ فبراير، ٢٠٢٠ ١١:٥٧ ص Ralph Schaer <notifications@github.com>
كتب:

**Comment by ralscha** [comment]
I can't reproduce it, but you could try and manually trigger change detection.
Inject `ChangeDetectorRef`
```
  constructor(....,
           private readonly changeDetectorRef: ChangeDetectorRef) {
  }
```

and then after the application sets the `this.myPhoto` variable trigger the change detection with either `detectChanges()` or `markForCheck()` 
```
      this.myPhoto = this.convertFileSrc(imageData);
      // this.changeDetectorRef.detectChanges();
      this.changeDetectorRef.markForCheck();
```

**Comment by azzmiazzmi** [comment]
Great, it worked exactly as I want.

**notice:** `detectChanges()`  worked for me while  `markForCheck()`  did not.

thanks
