### ISSUE TITLE
this.chart.destroy not a function

### ISSUE THREAD

**Issue by NexusInk** [ralscha/blog#3]
Hey Ralph, thanks for the good work here.

Have been able to reproduce and add (most) charts from the echarts example page on Ionic Tab app using your source code and from scratch

When updating to Echarts `3.6.0` I get the following runtime error when trying to view charts on an Ionic Sidemenu app:
`Uncaught (in promise): TypeError: this.chart.destroy is not a function TypeError: this.chart.destroy is not a function at EChartsComponent.ngOnDestroy `.

I'm not sure if this is an Echarts change since their update.

Thanks - not really an issue, more of a heads up.
Cheers

**Comment by NexusInk** [comment]
Managed a small hack on `echart-components.ts` with 
`ngOnDestroy(): void {
    window.removeEventListener('resize', this.resizeListener, true);
    this.chart.resize();
  }`
Refer to this Stackoverflow Q&A: [https://stackoverflow.com/questions/38158318/is-it-possible-to-use-echarts-baidu-with-angular-2-and-typescript](https://stackoverflow.com/questions/38158318/is-it-possible-to-use-echarts-baidu-with-angular-2-and-typescript)

This gets rid of runtime errors - but there are other bugs as well ;)

**Comment by ralscha** [comment]
Hi
Looks like there is now an angular directive for echarts 3.x
https://github.com/xieziyu/ngx-echarts

Maybe this is the better way going forward.

**Comment by NexusInk** [comment]
Thanks.

Your work has been of great value - your blog has been an eye opener.

**Comment by NexusInk** [comment]
Hey
Took a look at the ngx-echarts - pretty comprehensive - thanks.

Try this if you get the runtime error (from ngx-echarts):
`ngOnDestroy() {
    if (this.myChart) {
      this.myChart.dispose();
      this.myChart = null;
    }
  }`

It is a more consistent approach than my awkward hack.

**Comment by NexusInk** [comment]
`ngx-echarts` provides a wrapper for ECharts - very efficient for Angular Modules, but it feels like it's calling in an extra layer for Ionic to process.
Building out a custom component (like you did in your blog) seems more feasible.
Let me know what you think once you've played around with it.
I'll  be posting a repo with  `ngx-echarts/echarts` soon.
 Very handy solution, nonetheless.

**Comment by ralscha** [comment]
I changed the code of the blog to ngx-echarts. I like it better than my approach.
The only problem is that it does not automatically import the echarts library. 
One solution that I use now is copying the directive into my project and add an import statement
`import * as echarts from 'echarts/dist/echarts-en.js';`

Another solution is creating a custom copy config that copies the echarts library to the www directory and then reference it in the index.html

copy.config.js
```
module.exports = {
  copyEcharts: {
    src: ['./node_modules/echarts/dist/echarts-en.min.js'],
    dest: '{{WWW}}/build'
  }
}
```

package.json
```
   ...
  "config": {
    "ionic_copy": "./copy.config.js"
  },
  ...
```
