### ISSUE TITLE
cannot show the info  in HTML file when click number dot in the Echarts 

### ISSUE THREAD

**Issue by JerryMissTom** [ralscha/blog#4]
Hi ralscha, I have read your blog "Integrate Echarts into an Ionic3 app", it is nice and easy to understand. good work. 
I tried to use ECharts 3.X to draw chart in my app built with Ionic V3.3. When I click the number dot  in my chart, the related data will show in a field in HTML file. In the click event, I could get the data and copy it to a variable, but could not show value of the variable in HTML file. The screenshot of code is:
html 
![1](https://user-images.githubusercontent.com/15966403/27069212-6902b294-5046-11e7-8546-ae8c6e6dbf17.png)
ts
![2](https://user-images.githubusercontent.com/15966403/27069235-7b335144-5046-11e7-8c2b-c788744dcb92.png)
result 
![3](https://user-images.githubusercontent.com/15966403/27069328-d1a5ea8c-5046-11e7-975c-fc73e83d60c1.png)

but when I write  `this.text='hello world'` in ngOnInit()  method, it will show "hello world" without any problem. 
Did you ever met with this scene？

**Comment by ralscha** [comment]
Hi
Havn't experienced any problems so far, but I didn't do a lot with echarts so far.

I think in your example ```this``` in the listener does not point to the ContactPage. I guess this is the chart element

Try this instead
```
this.domMain.on('click', param => this.text = param.value + '');
```

**Comment by JerryMissTom** [comment]
it works!! Thank you very much, it help me a lot. This problem frustrates me all day.

**Comment by ralscha** [comment]
Glad I could help
